/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sonardemo;

import org.junit.Test;
import static org.assertj.core.api.Assertions.*;


public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertThat(classUnderTest.someLibraryMethod()).isTrue();
    }

    @Test
    public void messageShouldSayHelloWhenEnglish() {
        Library sut = new Library();
        assertThat(sut.getGreeting("en_US")).isEqualTo("Hello World");
    }

    @Test
    public void messageShouldSayHejWhenSwedish() {
        Library sut = new Library();
        assertThat(sut.getGreeting("sv_SE")).isEqualTo("Hej Världen");
    }

    @Test
    public void shouldThrowIfUnsupportedLanguage() {
        Library sut = new Library();
        assertThatExceptionOfType(IllegalArgumentException.class)
                .isThrownBy(() -> sut.getGreeting("unsupported"))
                .withMessage("Unsupported language");
    }

    @Test
    public void test1() {
        Library2 sut = new Library2();
        assertThat(sut.add(1,2)).isEqualTo(3);


    }
}
