/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sonardemo;

import org.junit.Test;
import static org.assertj.core.api.Assertions.*;


public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertThat(classUnderTest.someLibraryMethod()).isTrue();
    }

    @Test
    public void messageShouldSayHello() {
        Library sut = new Library();
        assertThat(sut.getMessage()).isEqualTo("Hello World");
    }
}
