/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sonardemo;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public String getMessage() {
        String message = "blue";


        return String.format("Hello World %s",message );
    }

}
