/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sonardemo;

import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public boolean unusedMethod() {
        Optional<String> opt = Optional.of("Dummy");
        if (opt != null) {
            Logger.getAnonymousLogger().log(Level.INFO, opt.get());
        }
        return true;
    }

    public String getGreeting(String lang) {
        switch (lang) {
            case "en_US":
                return "Hello World";
            case "sv_SE":
                return "Hej Världen";
            default:
                throw new IllegalArgumentException("Unsupported language");
        }

    }

    String doSomething(String [] strings) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < strings.length; i++) {
            sb.append(strings[i]+"-");
        }
        return sb.toString();
    }

}
